package com.org.model;


import java.util.Random;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class User {

//  Autogenerated Id
  private Long id = new Random().nextLong();
  private String username;
}
